### PR TITLE
reformat code with clang-format

### PR DESCRIPTION
**Pull request by skadge**
This should help ensuring an (automatically!) consistent coding style.

@JamesMcCrae, of course, happy to modify the configuration the way you prefer. I choose a C++ style configuration that I'm familiar with, but I don't mind using something else.

### CODE REVIEW

**Comment by JamesMcCrae** [comment]
This seems like a grand departure, standard practice is to adhere to the existing code standard and modify appropriately, e.g. a global reduction in tab spacing seems much. As an objective function: maybe minimize lines changed with a git diff (consistent but minimal in terms of changes)

**Comment by skadge** [comment]
@JamesMcCrae -- absolutely, my intent was not to modify significantly your original style, sorry, I should have spend more time tuning the uncrustify parameters to match the existing files.

I've update the PR with indents set to 4 spaces, and already the result is much closer to your files.

Happy to spend some more time fine-tuning -- tbh, I don't have any strong opinion on code formatting, but I do like consistency across the code base, and if I start working on code changes (I'll discuss them first, not worries!), I want to make sure the result will match the rest of the code.

(also, it would become very easy to add uncrustify to the github action, to check the PR for style before merging.)

**Comment by skadge** [comment]
Ok, after further investigation, using `clang-format` instead of `uncrustify` is probably a better choice (more common, and `.clang-format` is much easier to tune than `uncrustify.cfg`).

I've tuned `.clang-format` to try to match the existing style, making some choices where the existing source code was inconsistent (in eg brace positioning).

Please have a look, and feel free to suggest changes! 

For reference, the clang-format style guide is here: https://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Comment by JamesMcCrae** [comment]
Wonderful, static code analysis.

Did I make the "Most Vexing Parse" (10 years ago)?

Better to use clang-format

**Review by JamesMcCrae — APPROVED** [review]
Looks good overall!  There are a few places where the intended formatting for the comments is a bit off, but overall I think it's great to have everything formatted consistently.  Approved and merging.

**Pull request merged**
